name: Release on tag

on:
  push:
    tags:
      - v*

jobs:
  tests:
    name: Make checks 
    uses: ./.github/workflows/pull-request.yml

  build:
    needs: [tests]
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Get source code
        uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: latest

      - name: Cache NPM deps
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: node-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Install deps
        run: npm ci

      - name: Build app
        run: npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
  
  registry:
    name: Save to registry
    needs: [tests, build]
    outputs:
      changelog: ${{ steps.changelog.outputs.changelog }}

    if: |
      always() &&
      !contains(needs.*.result, 'cancelled')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Generate changelog
        id: changelog
        uses: metcalfc/changelog-generator@v4.1.0
        with:
          mytoken: ${{ secrets.GITHUB_TOKEN }}

      - name: Create an Issue
        id: issue
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ github.ref_name }} 
          CHANGELOG: ${{ steps.changelog.outputs.changelog }}
          CHECKS_LINK: ${{ needs.tests.outputs.link }}
        with:
          update_existing: true
          search_existing: all
      
      - name: Close created issue
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh issue close ${{ steps.issue.outputs.number }}

  release:
    name: Create release on Github
    needs: [registry]
    runs-on: ubuntu-latest
    steps:
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: latest

      - name: Cache NPM deps
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: node-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Install deps
        run: npm ci

      - name: Build app
        run: npm run build

      - name: Install zip
        run: sudo apt-get install zip -y

      - name: Zip build folder
        run: zip -r build.zip ./build
        
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body: ${{ needs.registry.outputs.changelog }}
          files: build.zip
          name: Release ${{ github.ref_name }}
        env:
          GITHUB_REPOSITORY: my_gh_org/my_gh_repo