name: Release on tag

on:
  push:
    tags:
      - v*

jobs:
  tests:
    name: Checks 
    runs-on: ubuntu-latest
    outputs:
      link: ${{ steps.checks.outputs.link }}
    steps:
      - name: Get source code
        uses: actions/checkout@v3

      - name: Make checks
        id: checks
        uses: ./.github/workflows/pull-request.yml

  build:
    needs: [tests]
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Get source code
        uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: latest

      - name: Cache NPM deps
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: node-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Install deps
        run: npm ci

      - name: Build app
        run: npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
  
  release:
    needs: [tests, build]
    if: |
      always() &&
      !contains(needs.*.result, 'failure') &&
      !contains(needs.*.result, 'cancelled')
    runs-on: ubuntu-latest
    steps:
      - name: Generate changelog
        id: changelog
        uses: metcalfc/changelog-generator@v4.1.0
        with:
          mytoken: ${{ secrets.GITHUB_TOKEN }}

      - name: Create an Issue
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ github.ref_name }} 
          CHANGELOG: ${{ steps.changelog.outputs.changelog }}
          CHECKS_LINK: $${{ needs.tests.outputs.link }}
        with:
          update_existing: true
          search_existing: all